// Generated by the protoc_message_enum.  DO NOT EDIT!
package bestan.common.protobuf;

public enum MessageEnum {
	INVALID,
	BaseProto,		//1
	RpcMessage,		//2
	DBTableDefine,		//3
	DBCommonKey,		//4
	CommonSave,		//5
	RpcCommonSaveOp,		//6
	RpcCommonSaveOpRes,		//7
	CommonSaveOp,		//8
	CommonLoadRes,		//9
	RpcCommonLoadOp,		//10
	RpcCommonLoadOpRes,		//11
}
