// Generated by the protoc_message_enum.  DO NOT EDIT!
package bestan.common.protobuf;

public enum MessageEnum {
	INVALID,
	BaseProto,		//1
	RpcMessage,		//2
	DBTableDefine,		//3
	DBCommonData,		//4
	DBCommonKey,		//5
	CommonSave,		//6
	RpcCommonSaveOp,		//7
	RpcCommonSaveOpRes,		//8
	CommonSaveOp,		//9
	CommonLoadRes,		//10
	RpcCommonLoadOp,		//11
	RpcCommonLoadOpRes,		//12
}
