// Generated by the protoc_message_enum.  DO NOT EDIT!
package bestan.common.protobuf;

public enum MessageEnum {
	INVALID,
	BaseProto,		//1
	BaseObjectProto,		//2
	RpcMessage,		//3
	DBTableDefine,		//4
	DBCommonData,		//5
	DBCommonKey,		//6
	CommonSave,		//7
	RpcCommonSaveOp,		//8
	RpcCommonSaveOpRes,		//9
	CommonSaveOp,		//10
	CommonLoadRes,		//11
	RpcCommonLoadOp,		//12
	RpcCommonLoadOpRes,		//13
}
